/**
 * Renaming a character, and what it does to the pipeline's two export trees.
 *
 * A character's NAME is baked into everything downstream of it: the DTH
 * Exporter writes `<base>.dth` / `.fbx` / `.abc` / `.zip`,
 * `<base>_experimental_rom.fbx`, `<base>_pose_asset.csv` and
 * `<base>_Hair_<item>_grooms.abc` per scene (measured on a real export folder),
 * where `<base>` is {@link exporterFigureName} plus the scene suffix. So a
 * rename does not just move a folder — it changes what every future export is
 * CALLED, which makes the files already on disk a set nothing will ever write
 * to again.
 *
 * The studio does not rename those files, and that is a decision rather than an
 * omission: their CONTENT names the old character too. Measured 2026-08-20 on a
 * real export (`Ita.dth`), the `.dth` carries `"Character Name": "Ita"` and
 * absolute `Fbx Rom Path` / `Alembic Rom Path` / `Experimental Rom Path`
 * entries pointing at its siblings — so a file-level rename would leave the HDA
 * importing a figure that still calls itself by the old name from paths that no
 * longer exist. The honest answer is the one the user asked for: wipe the old
 * set, and re-export.
 *
 * This module is the PURE half — which folders a rename clears, and the rails
 * that keep a recursive delete inside the character's own tree. The I/O half
 * (measuring them, deleting them, and following the rename into the Houdini
 * projects) is `api/rename.ts`.
 */

import { EXPORTS_FOLDER, LEGACY_EXPORTS_FOLDER } from '#/lib/scene-subfolder.ts'
import { hasParentTraversal, normalizePath, normalizePathLower } from '#/lib/path.ts'

/** One folder a rename clears, and what the dialog calls it. */
export interface ExportWipeTarget {
  /** Absolute folder path (normalized, original casing kept). */
  path: string
  /**
   * `daz` = the Daz→Houdini intermediate (`<char>/<houdini>/daz-export`), the
   * `.dth`/`.fbx`/`.abc` set a DazToHue network imports.
   * `final` = the character's `export/` folder, where Houdini writes what goes
   * to Unreal.
   */
  kind: 'daz' | 'final'
}

/**
 * The folders a rename clears — the two export trees, and nothing else.
 *
 * Both are DERIVED output: the Daz-side set is regenerated by a DTH Export run
 * and the final tree by the Houdini leg that follows it, which is precisely why
 * clearing them is recoverable while leaving them would not be (a stale set
 * outlives the name it was written for, and nothing ever sweeps it).
 *
 * Two roots are offered on the Daz side for the same reason `deleteCharacter`
 * offers two: a character that has not been saved since the export-root move
 * still has its files under the OLD location, and its own stored `exportPath`
 * is the precise answer for where they actually are.
 *
 * Every candidate has to clear three rails, mirroring the keep-flag delete's:
 *
 * - no `..` segment, so containment can be judged by prefix;
 * - INSIDE the character folder, never equal to it — `exportSubdir` is a
 *   per-project setting and an empty one resolves the final tree to the
 *   character folder ITSELF, which would turn a rename into a delete;
 * - and, for the Daz side only, NAMED like an export root (`daz-export` /
 *   `dth-exports`). `exportPath` is user data for any character not saved since
 *   schema v29 — it was a free directory picker whose natural answer was
 *   somewhere inside the Houdini folder, including that folder itself.
 *
 * The final tree needs no name rail because it is not user data: it is
 * `<char>/<exportSubdir>` with the subdir taken from the manifest, and the
 * "never the character folder" rail is what an empty subdir needs.
 *
 * Deduped case-insensitively while keeping the original spelling — the two Daz
 * roots coincide for an already-migrated character, and two recursive deletes
 * of one folder would race, but the path that gets deleted has to be the real
 * one (macOS is case-sensitive).
 */
export function exportWipeTargets(input: {
  /** The character's own folder — the containment rail for everything below. */
  charFolderAbs: string
  /** `characterExportRoot(...)` — where the exports belong today. */
  derivedExportRoot: string
  /** `character.exportPath` — where this character's definition says they are. */
  storedExportRoot: string
  /** `<charFolderAbs>/<exportSubdir>` — the final, Unreal-bound export tree. */
  finalExportDir: string
}): Array<ExportWipeTarget> {
  const folder = normalizePath(input.charFolderAbs)
  const folderKey = normalizePathLower(input.charFolderAbs)
  if (!folder) return []
  const inside = (p: string) => {
    if (!p.trim() || hasParentTraversal(p)) return false
    const key = normalizePathLower(p)
    return key !== folderKey && key.startsWith(`${folderKey}/`)
  }
  const namedLikeExportRoot = (p: string) => {
    const leaf = normalizePathLower(p).split('/').pop() ?? ''
    return leaf === EXPORTS_FOLDER.toLowerCase() || leaf === LEGACY_EXPORTS_FOLDER.toLowerCase()
  }
  const byKey = new Map<string, ExportWipeTarget>()
  // First spelling wins throughout — the DERIVED root leads the list because it
  // was computed from the folder that actually exists, while `exportPath` is
  // stored user data whose casing nothing has checked. On a case-SENSITIVE
  // filesystem only one of the two can be opened at all.
  const claim = (path: string, kind: ExportWipeTarget['kind']) => {
    const key = normalizePathLower(path)
    if (!byKey.has(key)) byKey.set(key, { path, kind })
  }
  for (const root of [input.derivedExportRoot, input.storedExportRoot]) {
    if (!inside(root) || !namedLikeExportRoot(root)) continue
    claim(normalizePath(root), 'daz')
  }
  // Claimed last, so a project whose `exportSubdir` somehow names the export
  // root is listed once as what it primarily is, never twice under two kinds.
  if (inside(input.finalExportDir)) claim(normalizePath(input.finalExportDir), 'final')
  return [...byKey.values()]
}

/** What one wipe target holds right now — the numbers the dialog shows so the
 *  user confirms an amount, not an abstraction (one scene's set is routinely a
 *  gigabyte; a final tree's `SKM_<name>.fbx` alone measured 178 MB). */
export interface ExportWipeMeasure extends ExportWipeTarget {
  files: number
  bytes: number
}

/** Whether a measured set is worth a dialog at all: no files, no warning — the
 *  rename just happens (there is nothing to lose and nothing to re-export). */
export function hasExportFiles(measured: ReadonlyArray<ExportWipeMeasure>): boolean {
  return measured.some((target) => target.files > 0)
}

/** `1.2 GB` / `340 MB` / `18 KB` — the dialog's sizes. Binary units, one
 *  decimal below 10 so "1.2 GB" doesn't round to a flat "1 GB". */
export function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  let value = bytes
  let unit = 0
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit += 1
  }
  const rounded = unit === 0 ? Math.round(value) : value < 10 ? Math.round(value * 10) / 10 : Math.round(value)
  return `${rounded} ${units[unit]}`
}

/**
 * The folder the character moved OUT of, or '' when it didn't move.
 *
 * The retarget swaps this prefix out of every absolute reference, so a wrong
 * value here rewrites paths belonging to something else entirely. Hence three
 * refusals, and '' meaning nothing more alarming than "no folder swap to make":
 * an empty answer, a `..` spelling (containment is judged by prefix on the
 * other side), and the same folder the character is in now — which is what a
 * rename that only changed the definition's `name` leaves behind, and what a
 * case-only rename looks like on a case-insensitive filesystem.
 */
export function movedFrom(previousFolder: string, folderAbs: string): string {
  const previous = previousFolder.trim()
  if (!previous || hasParentTraversal(previous)) return ''
  return normalizePathLower(previous) === normalizePathLower(folderAbs) ? '' : previous
}
