/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'
import { Route as ApiCharacterImagesFileNameRouteImport } from './routes/api.character-images.$fileName'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharacterImagesFileNameRoute =
  ApiCharacterImagesFileNameRouteImport.update({
    id: '/api/character-images/$fileName',
    path: '/api/character-images/$fileName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRoute
  '/api/character-images/$fileName': typeof ApiCharacterImagesFileNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRoute
  '/api/character-images/$fileName': typeof ApiCharacterImagesFileNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/characters/$id': typeof CharactersIdRoute
  '/api/character-images/$fileName': typeof ApiCharacterImagesFileNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/characters/$id'
    | '/api/character-images/$fileName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/characters/$id' | '/api/character-images/$fileName'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/characters/$id'
    | '/api/character-images/$fileName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CharactersIdRoute: typeof CharactersIdRoute
  ApiCharacterImagesFileNameRoute: typeof ApiCharacterImagesFileNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/character-images/$fileName': {
      id: '/api/character-images/$fileName'
      path: '/api/character-images/$fileName'
      fullPath: '/api/character-images/$fileName'
      preLoaderRoute: typeof ApiCharacterImagesFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CharactersIdRoute: CharactersIdRoute,
  ApiCharacterImagesFileNameRoute: ApiCharacterImagesFileNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
